package permission

func RegisterDefaultPermissions() {
	m := GlobalManager

	m.AddPermission(NewPermission("pocketmine.broadcast.admin", "Allows the user to receive administrative broadcasts", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.broadcast.user", "Allows the user to receive user broadcasts", DefaultTrue))

	m.AddPermission(NewPermission("pocketmine.command.help", "Allows the user to view the help menu", DefaultTrue))
	m.AddPermission(NewPermission("pocketmine.command.version", "Allows the user to view the version of the server", DefaultTrue))
	m.AddPermission(NewPermission("pocketmine.command.me", "Allows the user to perform a chat action", DefaultTrue))
	m.AddPermission(NewPermission("pocketmine.command.tell", "Allows the user to privately message another player", DefaultTrue))
	m.AddPermission(NewPermission("pocketmine.command.kill.self", "Allows the user to commit suicide", DefaultTrue))

	m.AddPermission(NewPermission("pocketmine.command.whitelist", "Allows the user to modify the server whitelist", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.whitelist.add", "Allows the user to add a player to the server whitelist", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.whitelist.remove", "Allows the user to remove a player to the server whitelist", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.whitelist.reload", "Allows the user to reload the server whitelist", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.whitelist.enable", "Allows the user to enable the server whitelist", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.whitelist.disable", "Allows the user to disable the server whitelist", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.whitelist.list", "Allows the user to list all the players on the server whitelist", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.ban", "Allows the user to ban people", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.ban.player", "Allows the user to ban players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.ban.ip", "Allows the user to ban IP addresses", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.ban.cid", "Allows the user to ban client IDs", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.unban", "Allows the user to unban people", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.unban.player", "Allows the user to unban players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.unban.ip", "Allows the user to unban IP addresses", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.unban.cid", "Allows the user to unban client IDs", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.op", "Allows the user to change operators", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.op.give", "Allows the user to give a player operator status", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.op.take", "Allows the user to take a players operator status", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.save", "Allows the user to save the worlds", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.save.enable", "Allows the user to enable automatic saving", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.save.disable", "Allows the user to disable automatic saving", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.save.perform", "Allows the user to perform a manual save", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.time", "Allows the user to alter the time", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.time.add", "Allows the user to fast-forward time", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.time.set", "Allows the user to change the time", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.time.start", "Allows the user to restart the time", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.time.stop", "Allows the user to stop the time", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.time.query", "Allows the user query the time", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.kill", "Allows the user to kill players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.kill.other", "Allows the user to kill other players", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.say", "Allows the user to talk as the console", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.give", "Allows the user to give items to players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.effect", "Allows the user to give/take potion effects", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.enchant", "Allows the user to enchant items", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.particle", "Allows the user to create particle effects", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.teleport", "Allows the user to teleport players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.kick", "Allows the user to kick players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.stop", "Allows the user to stop the server", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.list", "Allows the user to list all online players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.plugins", "Allows the user to view the list of plugins", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.reload", "Allows the user to reload the server settings", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.gamemode", "Allows the user to change the gamemode of players", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.defaultgamemode", "Allows the user to change the default gamemode", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.seed", "Allows the user to view the seed of the world", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.status", "Allows the user to view the server performance", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.tps", "Allows the user to view TPS", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.gc", "Allows the user to fire garbage collection tasks", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.dumpmemory", "Allows the user to dump memory contents", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.timings", "Allows the user to records timings for all plugin events", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.spawnpoint", "Allows the user to change player's spawnpoint", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.setworldspawn", "Allows the user to change the world spawn", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.weather", "Allows the user to change weather", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.xp", "Allows the user to manage experience", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.setblock", "Allows the user to set blocks", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.fill", "Allows the user to fill areas", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.summon", "Allows the user to summon entities", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.biome", "Allows the user to view biome info", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.chunkinfo", "Allows the user to view chunk info", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.lvdat", "Allows the user to manage level.dat", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.restart", "Allows the user to restart the server", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.backup", "Allows the user to backup the server", DefaultOp))

	m.AddPermission(NewPermission("pocketmine.command.extractphar", "", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.extractplugin", "", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.makeplugin", "", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.makeserver", "", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.generateplugin", "", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.bancidbyname", "", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.banipbyname", "", DefaultOp))
	m.AddPermission(NewPermission("pocketmine.command.loadplugin", "", DefaultOp))

	m.AddPermission(NewPermission("scaxe.command.luaplugin", "Allows the user to manage Lua plugins", DefaultOp))
}
